import Head from 'next/head';
import styles from '../../styles/Home.module.css';

import Nav from '../components/Nav';
import KosaricaSidebar from '../components/kosaricaSidebar';
import HeaderBanner from '../components/homepage/HeaderBanner';
import IzdvojeniProdukti from '../components/homepage/IzdvojeniProdukti';
import EmisijeBanner from '../components/homepage/EmisijeBanner';
import Partneri from '../components/homepage/Partneri';
import Kategorije from '../components/homepage/Kategorije';
import New from '../components/homepage/New';
import Vita from '../components/homepage/Vita';
import Social from '../components/homepage/Social';
import Blogs from '../components/homepage/Blogs';
import CallToAction from '../components/homepage/CallToAction';
import Footer from '../components/homepage/Footer';

import { client } from '../lib/client';

const Home = ({ banners, trendy, newProducts }) => {
  return (
    <>
      <Head>
        <title>Odaberi Zdravlje</title>
        <meta name="description" content="Generated by Odaberi Zdravlje" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Nav />
        <KosaricaSidebar />
        <HeaderBanner bannersField={banners} />
        <IzdvojeniProdukti trendyField={trendy} />
        <EmisijeBanner />
        <Partneri />
        <Kategorije />
        <New newField = {newProducts} />
        <Vita />
        <Blogs />
        <CallToAction />
        <Footer />
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  const bannerQuery = `*[_type == "banners"]`;
  const banners = await client.fetch(bannerQuery);

  const trendyQuery = `*[_type == "trendy"]`;
  const trendy = await client.fetch(trendyQuery);

  const newQuery = `*[_type == "trendy"]`;
  const newProducts = await client.fetch(newQuery);

  return {
    props: {
      banners,
      trendy,
      newProducts,
    },
  };
}

export default Home;