import Head from 'next/head';
import styles from '../../styles/Home.module.css';

import Nav from '../components/Nav';
import HeaderBanner from '../components/homepage/HeaderBanner';
import IzdvojeniProdukti from '../components/homepage/IzdvojeniProdukti';
import EmisijeBanner from '../components/homepage/EmisijeBanner';
import Partneri from '../components/homepage/Partneri';
import Kategorije from '../components/homepage/Kategorije';
import New from '../components/homepage/New';
import Vita from '../components/homepage/Vita';
import Social from '../components/homepage/Social';
import Blogs from '../components/homepage/Blogs';
import CallToAction from '../components/homepage/CallToAction';
import Footer from '../components/homepage/Footer';

import { Poppins } from '@next/font/google';

import { client } from '../lib/client';

const poppins = Poppins({ 
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
 });

const Home = ({ banneri, produkti }) => {
  return (
    <>
      <Head>
        <title>Odaberi Zdravlje</title>
        <meta name="description" content="Generated by Odaberi Zdravlje" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={poppins.className}>
        <Nav />
        <HeaderBanner banneri={banneri} />
        <IzdvojeniProdukti produkti={produkti} />
        <EmisijeBanner />
        <Partneri />
        <Kategorije />
        <New produkti = {produkti} />
        <Vita />
        <Blogs />
        <CallToAction />
        <Footer />
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  const bannerQuery = `*[_type == "banners"]`;
  const banneri = await client.fetch(bannerQuery);

  const produktiQuery = `*[_type == "produkt"]`;
  const produkti = await client.fetch(produktiQuery);

  return {
    props: {
      banneri,
      produkti,
    },
  };
}

export default Home;