import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';

import Nav from '../components/Nav';
import HeaderBanner from '../components/HeaderBanner';
import Trendy from '../components/Trendy';
import Video from '../components/Video';
import New from '../components/New';
import Social from '../components/Social';
import Blogs from '../components/Blogs';
import Footer from '../components/Footer';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Odaberi Zdravlje</title>
        <meta name="description" content="Generated by Odaberi Zdravlje" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Nav />
        <HeaderBanner />
        <Trendy />
        <Video />
        <New />
        <Social />
        <Blogs />
        <Footer />
      </main>
    </>
  )
}
